import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFile} from 'node:fs/promises';
import {giftCheckoutReturn} from '../assets/gift-checkout-model.js';
const script=(await readFile(new URL('../assets/gift-checkout.js',import.meta.url),'utf8')).replace(/^import .*;\n/,'');
async function page({seconds=120,balance=0,status='received',loggedIn=true,failOrder=false,query='?id=abc&package=gift_60',payUrl='https://buy.stripe.com/test'}={}){
 const elements=new Map(),calls=[],navigation=[];const el=selector=>{if(!elements.has(selector))elements.set(selector,{dataset:{},hidden:true,value:'',textContent:'',disabled:false});return elements.get(selector);};
 const ctx=vm.createContext({URL,URLSearchParams,window:{addEventListener(){}},document:{querySelector:el},location:{search:query,assign:url=>navigation.push(url)},sessionStorage:{setItem(){}},getAuthClient:async()=>({auth:{getSession:async()=>({data:{session:loggedIn?{user:{email:'test@example.com',email_confirmed_at:'today'}}:null}})}}),apiRequest:async(url,opts)=>{calls.push({url,opts});if(url==='/api/checkout')return {url:payUrl};if(failOrder)throw Error('No encontramos ese pedido en tu cuenta.');return {order:{targetSeconds:seconds,status,title:'Una historia de prueba'},seconds:{available:balance}};}});
 vm.runInContext(script,ctx);await new Promise(resolve=>setImmediate(resolve));return {el,calls,navigation,submit:()=>el('#checkout-form').onsubmit({preventDefault(){}})};
}
test('checkout uses saved order duration instead of query package and opens correct authenticated payment',async()=>{for(const seconds of [60,120]){const p=await page({seconds});assert.equal(p.el('#package-price').textContent,seconds===120?'$499':'$299');assert.equal(p.el('#checkout-email').value,'test@example.com');await p.submit();assert.equal(p.calls.at(-1).opts.body.plan,seconds===120?'gift_120':'gift_60');assert.deepEqual(p.navigation,['https://buy.stripe.com/test']);}});
test('existing balance or completed/reserved/cancelled order cannot trigger another purchase',async()=>{for(const config of [{balance:120},{status:'approved'},{status:'producing'},{status:'ready'},{status:'cancelled'}]){const p=await page(config);await p.submit();assert.equal(p.calls.some(c=>c.url==='/api/checkout'),false);assert.deepEqual(p.navigation,['/regalos/pedido/?id=abc']);}});
test('signed-out and inaccessible orders fail closed without payment calls',async()=>{for(const config of [{loggedIn:false},{failOrder:true}]){const p=await page(config);assert.equal(p.el('#checkout-pay').disabled,true);await p.submit();assert.equal(p.calls.some(c=>c.url==='/api/checkout'),false);assert.equal(p.navigation.length,0);}});
test('payment navigation accepts only Stripe HTTPS and restores retry after failure',async()=>{const p=await page({payUrl:'https://evil.example/pay'});await p.submit();assert.equal(p.navigation.length,0);assert.equal(p.el('#checkout-pay').disabled,false);assert.equal(p.el('#checkout-status').dataset.error,'true');});
test('login return preserves package or order without accepting open redirects',()=>{assert.equal(giftCheckoutReturn('{"plan":"gift_60"}'),'/regalos/checkout/?package=gift_60');assert.equal(giftCheckoutReturn('{"id":"https://evil.example"}'),'/regalos/checkout/?package=gift_120');assert.equal(giftCheckoutReturn('{"id":"b72ae29b-6a95-4961-904a-6fd3875eadd6"}'),'/regalos/checkout/?id=b72ae29b-6a95-4961-904a-6fd3875eadd6');});
test('both package controls update public checkout price, duration and Stripe plan',async()=>{const p=await page({query:'?package=gift_120'});await p.el('#choose-60').onchange();assert.equal(p.el('#package-price').textContent,'$299');assert.equal(p.el('#package-delivery').textContent,'Entrega en 24 horas*');await p.el('#choose-120').onchange();assert.equal(p.el('#package-price').textContent,'$499');await p.el('#choose-60').onchange();await p.submit();assert.equal(p.calls.at(-1).opts.body.plan,'gift_60');});
