import {readFile} from 'node:fs/promises';
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {database,user,call} from './helpers/database.mjs';
import {mockSupabase} from './helpers/supabase-http.mjs';
import {getGiftAdmin} from '../src/gift-admin.js';
import {getGiftOrder} from '../src/gift-orders.js';
import {giftRequest} from '../assets/gift-model.js';
import {projectData} from '../assets/studio-model.js';
let db,stub,original,admin,buyer,order,photo;
const env={SUPABASE_URL:'http://supabase.test',SUPABASE_SERVICE_ROLE_KEY:'test-only'};
before(async()=>{db=await database();await db.exec(await readFile(new URL('../supabase/migrations/20260922002237_gift_guest_checkout.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20260922015331_gift_whatsapp_delivery.sql',import.meta.url),'utf8'));stub=mockSupabase(db);original=globalThis.fetch;globalThis.fetch=stub.fetch;admin=await user(db);buyer=await user(db);admin.app_metadata={creativerush_gift_admin:true};stub.users.set(admin.id,admin);stub.users.set(buyer.id,buyer);photo=crypto.randomUUID();await call(db,'studio_write',[buyer.id,'register_asset',photo,JSON.stringify({kind:'image',name:'Mamá.png',bucket:'generation-references',storage_path:`${buyer.id}/${photo}.png`,mime_type:'image/png',size_bytes:100}),null]);const data=projectData(giftRequest({recipient:'Ana',names:'Ana y Lucía',occasion:'thanks',memory1:'Compartíamos el café.',message:'Gracias.',look:'3d',tone:'warm',ratio:'16:9'},[{id:photo,label:'Ana a la izquierda'}]));const p=await call(db,'studio_write',[buyer.id,'create_project',crypto.randomUUID(),JSON.stringify(data),null]);order=await call(db,'gift_order_customer',[buyer.id,p.id,'submit']);});
after(async()=>{globalThis.fetch=original;await db.close();});
function context(u,path=''){return {env,request:new Request('https://app.test/api/gift-admin'+path,{headers:u?{authorization:'Bearer '+u.id}:{}})};}
test('anonymous/customer cannot read orders or photos; editable metadata cannot become admin',async()=>{assert.equal((await getGiftAdmin(context(null))).status,401);for(const path of ['', '?id='+order.id,'?id='+order.id+'&download=1'])assert.equal((await getGiftAdmin(context(buyer,path))).status,403);buyer.user_metadata={creativerush_gift_admin:true};assert.equal((await getGiftAdmin(context(buyer))).status,403);buyer.app_metadata={creativerush_gift_admin:'true'};assert.equal((await getGiftAdmin(context(buyer))).status,403);});
test('authorized administrator sees brief, owner email and private owned reference URLs',async()=>{const response=await getGiftAdmin(context(admin,'?id='+order.id));assert.equal(response.status,200);assert.match(response.headers.get('cache-control'),/no-store/);const {order:o}=await response.json();assert.match(o.brief.idea,/Compartíamos el café/);assert.equal(o.customerEmail,buyer.email);assert.match(o.photos[0].url,/test-private/);assert.ok(!JSON.stringify(o).includes('test-only'));const own=await getGiftOrder(context(admin,'?id='+order.id));assert.equal(own.status,404);});
test('revoked admin loses access immediately, and incomplete movies cannot be downloaded',async()=>{admin.app_metadata={};assert.equal((await getGiftAdmin(context(admin))).status,403);admin.app_metadata={creativerush_gift_admin:true};assert.equal((await getGiftAdmin(context(admin,'?id='+order.id+'&download=1'))).status,409);assert.equal((await getGiftAdmin(context(admin,'?id=bad'))).status,400);});
test('a forged reference from a different owner cannot be signed even by the panel',async()=>{const bad=crypto.randomUUID();await call(db,'studio_write',[admin.id,'register_asset',bad,JSON.stringify({kind:'image',name:'private.png',bucket:'generation-references',storage_path:`${admin.id}/${bad}.png`,mime_type:'image/png',size_bytes:100}),null]);await db.query("update gift_orders set brief=jsonb_set(brief,'{creativeMemory,characterAssetIds}',$2::jsonb) where id=$1",[order.id,JSON.stringify([bad])]);assert.notEqual((await getGiftAdmin(context(admin,'?id='+order.id))).status,200);await db.query("update gift_orders set brief=jsonb_set(brief,'{creativeMemory,characterAssetIds}',$2::jsonb) where id=$1",[order.id,JSON.stringify([photo])]);});
test('pagination and status filters expose all orders without repeating a page',async()=>{for(let i=0;i<52;i++){const id=crypto.randomUUID();await db.query('insert into studio_projects(id,user_id,data,brand_snapshot) select $1,user_id,data,brand_snapshot from studio_projects where id=$2',[id,order.id]);await db.query("insert into gift_orders(id,user_id,brief,target_seconds,status) select $1,user_id,brief,60,'cancelled' from gift_orders where id=$2",[id,order.id]);}const first=await (await getGiftAdmin(context(admin,'?status=cancelled'))).json(),second=await (await getGiftAdmin(context(admin,'?status=cancelled&page=1'))).json();assert.equal(first.orders.length,50);assert.equal(first.hasMore,true);assert.equal(second.orders.length,2);assert.equal(second.hasMore,false);assert.equal(new Set([...first.orders,...second.orders].map(o=>o.id)).size,52);const received=await (await getGiftAdmin(context(admin,'?status=received'))).json();assert.equal(received.orders.length,1);assert.equal((await getGiftAdmin(context(admin,'?page=-1'))).status,400);assert.equal((await getGiftAdmin(context(admin,'?status=bogus'))).status,400);});

test('configured admin email requires verified ownership and cannot be spoofed in metadata',async()=>{
 const configured={...env,GIFT_ADMIN_EMAILS:buyer.email};
 let c=context(buyer);c.env=configured;buyer.user_metadata={email:buyer.email,email_verified:true};
 assert.equal((await getGiftAdmin(c)).status,403);
 buyer.email_confirmed_at=new Date().toISOString();assert.equal((await getGiftAdmin(c)).status,200);
 buyer.email_confirmed_at=null;assert.equal((await getGiftAdmin(c)).status,403);
 c.env={...env,GIFT_ADMIN_EMAILS:'different@example.test'};buyer.email_confirmed_at=new Date().toISOString();assert.equal((await getGiftAdmin(c)).status,403);
});
