import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {database,user,call} from './helpers/database.mjs';
import {mockSupabase} from './helpers/supabase-http.mjs';
import {giftRequest} from '../assets/gift-model.js';
import {projectData} from '../assets/studio-model.js';
import {getGiftOrder,postGiftOrder} from '../src/gift-orders.js';
let db,stub,original;
const env={SUPABASE_URL:'http://supabase.test',SUPABASE_SERVICE_ROLE_KEY:'test-only'};
before(async()=>{db=await database();await db.exec(await readFile(new URL('../supabase/migrations/20260922002237_gift_guest_checkout.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20260922015331_gift_whatsapp_delivery.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20260922020036_gift_whatsapp_after_payment.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20260922165737_gift_payment_first.sql',import.meta.url),'utf8'));stub=mockSupabase(db);original=globalThis.fetch;globalThis.fetch=stub.fetch;});
after(async()=>{globalThis.fetch=original;await db.close();});
async function fixture(seconds=60){const u=await user(db);stub.users.set(u.id,u);await db.query('update credit_balances set seconds_plan=true,video_seconds=$2 where user_id=$1',[u.id,seconds]);const p=await call(db,'studio_write',[u.id,'create_project',crypto.randomUUID(),JSON.stringify(projectData(giftRequest({recipient:'Ana',names:'Ana y Lucía',occasion:'thanks',memory1:'Compartíamos café antes de ir al autobús.',message:'Gracias, mamá.',look:'3d',tone:'warm',ratio:'16:9'}))),null]);return {u,p};}
const customer=(f,action,expected=null,note='')=>call(db,'gift_order_customer',[f.u.id,f.p.id,action,expected,note]);
const operator=(f,action,expected,data={})=>call(db,'gift_order_operator',[f.p.id,action,expected,JSON.stringify(data)]);
const balance=async f=>(await db.query('select video_seconds from credit_balances where user_id=$1',[f.u.id])).rows[0].video_seconds;
async function approve(f){await customer(f,'submit');const o=await operator(f,'script',1,{script:'Mamá, gracias por compartir todas las mañanas conmigo.'});await customer(f,'approve',o.revision);return o;}
async function asset(f,duration=58){const id=crypto.randomUUID();await call(db,'studio_write',[f.u.id,'register_asset',id,JSON.stringify({kind:'clip',name:'Mi película',bucket:'studio-media',storage_path:`${f.u.id}/${id}.mp4`,mime_type:'video/mp4',size_bytes:1000,duration_seconds:duration}),null]);return id;}
function request(f,path='',body){return {env,request:new Request('https://app.test/api/gift-orders'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+f.u.id,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})})};}
test('intake is idempotent, owned, free, and cannot launch automatic generation',async()=>{const f=await fixture();assert.equal((await customer(f,'submit')).status,'received');assert.equal((await customer(f,'submit')).revision,1);assert.equal(await balance(f),60);await assert.rejects(call(db,'studio_chat_prepare',[f.u.id,crypto.randomUUID(),f.p.id,JSON.stringify({expected:1,message:'Produce',enabled:true})]),/GIFT_MANUAL/);await assert.rejects(call(db,'studio_production_start',[f.u.id,crypto.randomUUID(),f.p.id,1,true]),/GIFT_MANUAL/);const other=await fixture();await assert.rejects(call(db,'gift_order_customer',[other.u.id,f.p.id,'submit',null,'']),/GIFT_NOT_FOUND/);assert.equal((await db.query('select count(*)::int n from studio_productions')).rows[0].n,0);});
test('approval requires funds and the current script; repeated approval charges once',async()=>{const f=await fixture(12);await customer(f,'submit');await assert.rejects(customer(f,'approve',1),/GIFT_INVALID/);const o=await operator(f,'script',1,{script:'Gracias por cuidarme, mamá.'});await assert.rejects(customer(f,'approve',1),/GIFT_CONFLICT/);await assert.rejects(customer(f,'approve',o.revision),/GIFT_BALANCE/);assert.equal(await balance(f),12);await customer(f,'changes',o.revision,'Añade nuestra cocina.');await assert.rejects(customer(f,'approve',o.revision),/GIFT_CONFLICT/);const revised=await operator(f,'script',3,{script:'En nuestra cocina aprendí lo que es cuidar.'});await db.query('update credit_balances set video_seconds=60 where user_id=$1',[f.u.id]);await customer(f,'approve',revised.revision);await customer(f,'approve',revised.revision);assert.equal(await balance(f),0);});
test('delivery requires production, owned MP4 and duration; settles once and gates private download',async()=>{const f=await fixture(),o=await approve(f),a=await asset(f);assert.equal((await getGiftOrder(request(f,'?id='+f.p.id+'&download=1'))).status,400);await assert.rejects(operator(f,'deliver',o.revision,{assetId:a,reviewNote:'Revisado'}),/GIFT_INVALID/);await operator(f,'start',o.revision);const other=await fixture(),foreign=await asset(other),long=await asset(f,61);await assert.rejects(operator(f,'deliver',o.revision,{assetId:foreign,reviewNote:'Revisado'}),/GIFT_ASSET/);await assert.rejects(operator(f,'deliver',o.revision,{assetId:long,reviewNote:'Revisado'}),/GIFT_DURATION/);await operator(f,'deliver',o.revision,{assetId:a,reviewNote:'Audio completo y visuales revisados.'});await operator(f,'deliver',o.revision,{assetId:a,reviewNote:'Reintento'});assert.equal(await balance(f),2);const download=await getGiftOrder(request(f,'?id='+f.p.id+'&download=1'));assert.equal(download.status,200);assert.match((await download.json()).url,/test-private/);assert.equal((await getGiftOrder(request(other,'?id='+f.p.id+'&download=1'))).status,404);});
test('cancelling releases the reservation once and operator commands stay private',async()=>{const f=await fixture(),o=await approve(f);await operator(f,'cancel',o.revision);await operator(f,'cancel',o.revision);assert.equal(await balance(f),60);assert.equal((await postGiftOrder(request(f,'',{id:f.p.id,action:'deliver',expected:o.revision}))).status,400);await db.exec('set role authenticated');try{await assert.rejects(operator(f,'start',o.revision),/permission denied/);await assert.rejects(db.query('select * from gift_orders'),/permission denied/);}finally{await db.exec('reset role');}});
test('gift form submits an order without invoking a language or media provider',async()=>{const source=await readFile(new URL('../assets/gifts.js',import.meta.url),'utf8');assert.ok(source.includes("apiRequest('/api/gift-orders'"));assert.ok(!source.includes('/api/studio-chat'));});
