import {test} from 'node:test';
import assert from 'node:assert/strict';
import {modelFetch,responsesRequest} from '../src/model-provider.js';
import {WORKFLOW_MODEL,SCRIPT_MODEL} from '../assets/model-routing.js';
import {CHAT_MODEL} from '../assets/chat-model.js';
import {FLASH_MODEL} from '../assets/reference-model.js';
import {readEvents} from '../assets/chat-stream.js';
import {callEditor} from '../src/studio-chat.js';
const sse=events=>new Response(events.map(d=>'data: '+JSON.stringify(d)+'\n\n').join(''));
function toolResponse(name,args,model=WORKFLOW_MODEL){const item={type:'function_call',call_id:'call_1',name,arguments:JSON.stringify(args)};return sse([{type:'response.created',response:{model}},{type:'response.output_item.added',output_index:0,item},{type:'response.function_call_arguments.delta',output_index:0,delta:item.arguments},{type:'response.completed',response:{model,status:'completed',output:[item],usage:{input_tokens:11,output_tokens:13}}}]);}
test('workflow and reference select Luna; script retains independent previous model',()=>{assert.equal(CHAT_MODEL,WORKFLOW_MODEL);assert.equal(FLASH_MODEL,WORKFLOW_MODEL);assert.notEqual(SCRIPT_MODEL,WORKFLOW_MODEL);});
test('Responses preserves image evidence and multi-turn tool results',()=>{const r=responsesRequest({model:WORKFLOW_MODEL,messages:[{role:'user',content:[{type:'text',text:'inspect'},{type:'image_url',image_url:{url:'data:image/png;base64,abc'}}]},{role:'assistant',content:null,tool_calls:[{id:'c1',function:{name:'inspect',arguments:'{}'}}]},{role:'tool',tool_call_id:'c1',content:'ok'}],tools:[{type:'function',function:{name:'inspect',parameters:{type:'object'}}}],tool_choice:'required'});assert.equal(r.input[0].content[1].image_url,'data:image/png;base64,abc');assert.equal(r.input[1].call_id,r.input[2].call_id);assert.equal(r.tools[0].name,'inspect');assert.equal(r.store,false);});
test('Responses tool deltas stream once with actual model and usage',async()=>{let body,url;const r=await modelFetch(async(u,i)=>{url=u;body=JSON.parse(i.body);return toolResponse('edit',{x:1});},'https://opencode.ai/zen/go/v1/chat/completions',{body:JSON.stringify({model:WORKFLOW_MODEL,messages:[]})});const events=[];await readEvents(r,d=>events.push(d));assert.match(url,/\/responses$/);assert.equal(body.model,WORKFLOW_MODEL);assert.equal(events.flatMap(d=>d.choices||[]).flatMap(c=>c.delta.tool_calls||[]).map(t=>t.function.arguments).join(''),'{"x":1}');assert.equal(events.at(-1).usage.prompt_tokens,11);assert.equal(events.at(-1).choices[0].finish_reason,'tool_calls');});
test('incomplete Responses stream cannot become a successful edit',async()=>{const r=await modelFetch(async()=>sse([{type:'response.created',response:{model:WORKFLOW_MODEL}}]),'https://opencode.ai/zen/go/v1/chat/completions',{body:JSON.stringify({model:WORKFLOW_MODEL,messages:[]})});await assert.rejects(readEvents(r,()=>{}),/Truncated/);});
test('script drafting delegates to script model and only its copy reaches preview/result',async()=>{const seen=[],deltas=[];const project={id:'p',revision:1,brand_snapshot:{},data:{scenes:[],creative:{},scriptDraft:''}};
 const request=async(url,init)=>{const b=JSON.parse(init.body);seen.push(b.model);if(b.model===WORKFLOW_MODEL)return toolResponse('edit_project',{operation:'draft_script',message:'Preparando el guion.',value:'Write a concise hook'});assert.equal(b.tools[0].function.name,'write_script');return sse([{model:SCRIPT_MODEL,choices:[{delta:{tool_calls:[{index:0,function:{name:'write_script',arguments:JSON.stringify({value:'Este es el guion final.'})}}]},finish_reason:'tool_calls'}],usage:{prompt_tokens:5,completion_tokens:6}}]);};
 const result=await callEditor(project,[],[],'Haz un guion',{REFERENCE_FLASH_KEY:'fixture'},request,d=>deltas.push(d));assert.deepEqual(seen,[WORKFLOW_MODEL,SCRIPT_MODEL]);assert.equal(result.edit.value,'Este es el guion final.');assert.equal(deltas.filter(d=>d.field==='script').map(d=>d.text).join(''),'Este es el guion final.');assert.equal(result.usage.prompt_tokens,16);
});
test('visual edits stay with Luna without calling script model',async()=>{let n=0;const result=await callEditor({id:'p',revision:1,brand_snapshot:{},data:{scenes:[],creative:{}}},[],[],'En plastilina',{REFERENCE_FLASH_KEY:'fixture'},async()=>{n++;return toolResponse('edit_project',{operation:'set_look',message:'Listo',value:'clay'});});assert.equal(n,1);assert.equal(result.edit.operation,'set_look');});
test('batch hook and scene narration use the writer; visual change remains Luna output',async()=>{
 const models=[];const sceneId='11111111-1111-4111-8111-111111111111';const project={id:'p',revision:1,brand_snapshot:{},data:{scenes:[{id:sceneId,text:'Original'}],creative:{}}};
 const fetchImpl=async(url,init)=>{const body=JSON.parse(init.body);models.push(body.model);if(body.model===WORKFLOW_MODEL)return toolResponse('edit_project',{operation:'batch',message:'Cambios preparados',changes:[{operation:'set_hook',value:'Short hook'},{operation:'edit_text',sceneId,value:'Short narration'},{operation:'set_look',value:'clay'}]});return sse([{model:SCRIPT_MODEL,choices:[{delta:{tool_calls:[{index:0,function:{name:'write_script',arguments:JSON.stringify({value:'Texto del escritor.'})}}]},finish_reason:'tool_calls'}]}]);};
 const result=await callEditor(project,[],[],'Acorta y usa plastilina',{REFERENCE_FLASH_KEY:'fixture'},fetchImpl);assert.deepEqual(models,[WORKFLOW_MODEL,SCRIPT_MODEL,SCRIPT_MODEL]);assert.equal(result.edit.changes[0].value,'Texto del escritor.');assert.equal(result.edit.changes[1].value,'Texto del escritor.');assert.equal(result.edit.changes[2].value,'clay');assert.equal(result.usage.calls[1].usage,null);
});
test('writer failure never falls back to coordinator instructions as narration',async()=>{
 let n=0;await assert.rejects(callEditor({id:'p',revision:1,brand_snapshot:{},data:{scenes:[],creative:{}}},[],[],'Guion',{REFERENCE_FLASH_KEY:'fixture'},async()=>++n===1?toolResponse('edit_project',{operation:'draft_script',message:'Preparando',value:'Editorial instruction'}):new Response('',{status:503})),/CHAT_PROVIDER/);assert.equal(n,2);
});
