import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {database,user,call} from './helpers/database.mjs';
import {mockSupabase} from './helpers/supabase-http.mjs';
import {sampleFrames,validateAnalysis,parseModelJson,referenceDirection,FLASH_MODEL} from '../assets/reference-model.js';
import {monoWav} from '../assets/reference-media.js';
import {getReferenceAnalysis,postReferenceAnalysis,validateInput,modelRequest} from '../src/reference-analysis.js';
import {postStudio} from '../src/studio.js';
let db,stub,original,providerCalls,asrCalls,output,finish,model;
const env={SUPABASE_URL:'http://supabase.test',SUPABASE_SERVICE_ROLE_KEY:'test-key',REFERENCE_ANALYSIS_ENABLED:'true',REFERENCE_FLASH_KEY:'private-flash',REFERENCE_SCRIBE_KEY:'private-scribe'};
const valid=()=>({topic:'Filtro de ducha de la referencia',hook:'Cabello en la mano',style:'Plastilina cálida',characters:['Adulto, camiseta clara'],beats:[{frameIds:sampleFrames(6).map(f=>f.id),visual:'Presenta el producto'}],cta:'Compra según la narración',sourceClaims:['Promesa de la referencia, sin verificar'],uncertainties:['No se conoce movimiento entre muestras']});
before(async()=>{db=await database();stub=mockSupabase(db);original=globalThis.fetch;globalThis.fetch=async(input,options={})=>{const url=typeof input==='string'?input:input.url;
 if(url.startsWith('https://api.elevenlabs.io/')){asrCalls++;assert.equal(options.headers['xi-api-key'],'private-scribe');return Response.json({words:[{type:'word',text:'Referencia',start:0,end:1}]});}
 if(url.startsWith('https://opencode.ai/')){providerCalls++;const request=JSON.parse(options.body);assert.equal(request.model,FLASH_MODEL);assert.equal(request.messages[1].content.filter(c=>c.type==='image_url').length,4);return new Response('data: '+JSON.stringify({model:model||FLASH_MODEL,choices:[{delta:{content:JSON.stringify(output||valid()),reasoning_content:'must-not-be-saved'},finish_reason:finish||'stop'}],usage:{prompt_tokens:100,completion_tokens:100}})+'\n\ndata: [DONE]\n');}
 return stub.fetch(input,options);
};});
after(async()=>{globalThis.fetch=original;await db.close();});
function ctx(body,token,extra={}){return {env:{...env,...extra},request:new Request('https://app.test/api/reference-analysis',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(body)})};}
async function fixture(){const u=await user(db),token=u.id;stub.users.set(token,u);const brandId=crypto.randomUUID();await call(db,'studio_write',[u.id,'save_brand',brandId,JSON.stringify({name:'Nuestra marca',product:'Filtro',appearance:'Cromo',claims:'Nuestra afirmación aprobada'})]);const p=await call(db,'studio_write',[u.id,'create_project',crypto.randomUUID(),JSON.stringify({title:'Anuncio',brandId,referenceUrl:'',referenceNotes:'Dirección anterior',aspectRatio:'9:16',scenes:[],timingConfirmed:false})]);providerCalls=asrCalls=0;output=null;finish=null;model=null;return {u,token,p};}
function body(p,extra={}){return {projectId:p.id,requestId:crypto.randomUUID(),source:{name:'video.mp4',sha256:'a'.repeat(64),duration:6,width:360,height:640},frames:sampleFrames(6),sheets:Array(4).fill('data:image/jpeg;base64,/9j/'),audio:Buffer.from(monoWav(new Float32Array(96000))).toString('base64'),silent:false,...extra};}
test('rejects 0–0 / missing / repeated / reordered frame sequences; accepts known IDs only',()=>{const frames=sampleFrames(6);const base=valid();assert.equal(validateAnalysis('```json\n'+JSON.stringify(base)+'\n```',frames).beats[0].observedTo,5.8);assert.deepEqual(parseModelJson('Resultado:\n'+JSON.stringify(base)),base);for(const beats of [[{from_s:0,to_s:0,visual:'x'}],[{frameIds:['F01','F03'],visual:'x'}],[{frameIds:['F01','F01'],visual:'x'}],[{frameIds:frames.map(f=>f.id).reverse(),visual:'x'}]])assert.throws(()=>validateAnalysis({...base,beats},frames),/REFERENCE_OUTPUT_INVALID/);assert.throws(()=>parseModelJson(JSON.stringify(base)+' trailing'),/REFERENCE_OUTPUT_INVALID/);});
test('validated input bounds audio, image payloads and timestamps before calling providers',()=>{const p={id:crypto.randomUUID()},b=body(p);assert.equal(validateInput(b).audio.length,192044);for(const x of [{source:{...b.source,duration:999}},{frames:b.frames.map(f=>({...f,time:0}))},{sheets:['https://private.example/secret']},{audio:'AAAA'},{silent:true,audio:b.audio}])assert.throws(()=>validateInput({...b,...x}),/REFERENCE_INVALID/);const nine={...b,source:{...b.source,duration:25},frames:sampleFrames(25),sheets:b.sheets.slice(0,3),silent:true,audio:null};assert.equal(modelRequest(validateInput(nine),{mode:'declared_silent',text:''}).messages[1].content.filter(c=>c.type==='image_url').length,3);});
test('auth and ownership reject requests before any ASR or Flash call',async()=>{const a=await fixture(),b=await fixture();assert.equal((await postReferenceAnalysis(ctx(body(a.p),'invalid'))).status,401);assert.equal((await postReferenceAnalysis(ctx(body(a.p),b.token))).status,404);assert.equal(providerCalls+asrCalls,0);});
test('same request replays stored success even in maintenance; changed payload conflicts',async()=>{const f=await fixture(),b=body(f.p);const r=await postReferenceAnalysis(ctx(b,f.token));assert.equal(r.status,200,await r.clone().text());const a=(await r.json()).analysis;assert.equal(a.result.reviewRequired,true);assert.equal(a.result.beats[0].observedTo,5.8);assert.equal(a.transcript.text,'Referencia');assert.equal(providerCalls,1);assert.equal(asrCalls,1);const retry=await postReferenceAnalysis(ctx(b,f.token,{REFERENCE_ANALYSIS_ENABLED:'false'}));assert.equal(retry.status,200);assert.equal((await retry.json()).analysis.id,a.id);assert.equal(providerCalls,1);assert.equal(asrCalls,1);assert.equal((await postReferenceAnalysis(ctx({...b,silent:true,audio:null},f.token))).status,409);assert.equal((await db.query('select data from studio_projects where id=$1',[f.p.id])).rows[0].data.referenceNotes,'Dirección anterior');});
test('truncated or invalid model output stays unusable and retry never calls a provider twice',async()=>{for(const failure of ['length','invalid']){const f=await fixture(),b=body(f.p);if(failure==='length')finish='length';else output={...valid(),beats:[{frameIds:['F01'],visual:'Incomplete'}]};const r=await postReferenceAnalysis(ctx(b,f.token));assert.equal(r.status,422);assert.equal((await db.query('select status from studio_reference_analyses where id=$1',[b.requestId])).rows[0].status,'invalid');const retry=await postReferenceAnalysis(ctx(b,f.token));assert.equal(retry.status,200);assert.equal((await retry.json()).analysis.status,'invalid');assert.equal(providerCalls,1);}});
test('provider model substitution is rejected',async()=>{const f=await fixture();model='deepseek-v4-flash';assert.equal((await postReferenceAnalysis(ctx(body(f.p),f.token))).status,422);});
test('declared narration-free input bypasses ASR with an explicit evidence limitation',async()=>{const f=await fixture();const r=await postReferenceAnalysis(ctx(body(f.p,{silent:true,audio:null}),f.token));assert.equal(r.status,200);assert.equal((await r.json()).analysis.transcript.mode,'declared_silent');assert.equal(asrCalls,0);assert.equal(providerCalls,1);});
test('review adoption preserves scenes, versions, timing and brand and fences concurrent edits',async()=>{const f=await fixture(),b=body(f.p);await postReferenceAnalysis(ctx(b,f.token));const before=(await db.query('select * from studio_projects where id=$1',[f.p.id])).rows[0];const r=await postReferenceAnalysis(ctx({action:'adopt',id:b.requestId,projectId:f.p.id,expected:before.revision,notes:'Caricatura 3D cálida; persona original.'},f.token));assert.equal(r.status,200,await r.clone().text());const after=(await r.json()).project;assert.deepEqual(after.data.scenes,before.data.scenes);assert.deepEqual(after.brand_snapshot,before.brand_snapshot);assert.equal(after.data.timingConfirmed,before.data.timingConfirmed);assert.equal(after.data.referenceAnalysisId,b.requestId);assert.equal(after.data.referenceNotes,'Caricatura 3D cálida; persona original.');assert.equal((await postReferenceAnalysis(ctx({action:'adopt',id:b.requestId,projectId:f.p.id,expected:before.revision,notes:'stale'},f.token))).status,409);const save=await postStudio({env,request:new Request('https://app.test/api/studio',{method:'POST',headers:{authorization:'Bearer '+f.token,'content-type':'application/json'},body:JSON.stringify({action:'save_project',id:after.id,expected:after.revision,data:{...after.data,title:'Título nuevo'}})})});assert.equal(save.status,200,await save.clone().text());assert.equal((await save.json()).value.data.referenceAnalysisId,b.requestId);assert.ok(!referenceDirection(validateAnalysis(valid(),sampleFrames(6))).includes('Promesa de la referencia'));});
test('active request and daily quota prevent more provider calls; expired request is uncertain, never reclaimed',async()=>{const f=await fixture(),b=body(f.p);const reserve=()=>call(db,'studio_reference_write',[f.u.id,'reserve',b.requestId,f.p.id,JSON.stringify({hash:'a'.repeat(64),source:b.source,enabled:true})]);assert.equal((await reserve()).claimed,true);assert.equal((await reserve()).claimed,false);assert.equal((await postReferenceAnalysis(ctx(body(f.p),f.token))).status,409);assert.equal(providerCalls,0);await db.query("update studio_reference_analyses set started_at=now()-interval '5 minutes' where id=$1",[b.requestId]);const result=await getReferenceAnalysis({env,request:new Request('https://app.test/api/reference-analysis?project='+f.p.id,{headers:{authorization:'Bearer '+f.token}})});assert.equal((await result.json()).analyses[0].status,'uncertain');for(let i=0;i<4;i++){const r=await postReferenceAnalysis(ctx(body(f.p),f.token));assert.equal(r.status,200);}assert.equal((await postReferenceAnalysis(ctx(body(f.p),f.token))).status,429);assert.equal(providerCalls,4);});
test('analysis tables have RLS, browser cannot read other data or call privileged RPC, and source claims are never auto-approved',async()=>{const f=await fixture();await postReferenceAnalysis(ctx(body(f.p),f.token));await db.exec('set role authenticated');try{await assert.rejects(db.query('select * from studio_reference_analyses'),/permission denied/);await assert.rejects(call(db,'studio_reference_write',[f.u.id,'reserve',crypto.randomUUID(),f.p.id,'{}']),/permission denied/);}finally{await db.exec('reset role');}const flag=(await db.query("select relrowsecurity from pg_class where relname='studio_reference_analyses'")).rows[0];assert.equal(flag.relrowsecurity,true);const stored=(await db.query('select * from studio_reference_analyses where user_id=$1',[f.u.id])).rows[0];assert.ok(!JSON.stringify(stored).includes('private-flash'));assert.ok(!JSON.stringify(stored).includes('must-not-be-saved'));assert.equal(stored.adopted_at,null);});

test('binary WAV lengths cannot shift magic offsets through UTF-8 decoding',()=>{for(const duration of [36.038188,36.246,48.4,90.969938,120]){const b=body({id:crypto.randomUUID()});b.source.duration=duration;b.frames=sampleFrames(duration);b.audio=Buffer.from(monoWav(new Float32Array(Math.ceil(duration*16000)))).toString('base64');assert.ok(validateInput(b).audio.length>44);}});
