import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {database,user,ready,balance} from './helpers/database.mjs';
import {CHAT_MODEL} from '../assets/chat-model.js';
import {mockSupabase} from './helpers/supabase-http.mjs';
import {getStudio,postStudio} from '../src/studio.js';
import {onRequestPost as renderWorker} from '../functions/api/studio-worker.js';
let db,stub,original,flashCalls=0,rejectFlash=false;const env={SUPABASE_URL:'http://supabase.test',SUPABASE_SERVICE_ROLE_KEY:'test-only-server',GENERATION_ENABLED:'true',PRODUCTION_WORKFLOW_PROFILE:'sol-luna-v1',REFERENCE_FLASH_KEY:'test-only',STUDIO_WORKER_TOKEN:'studio-worker-test-secret-min-32-characters'};
before(async()=>{db=await database();stub=mockSupabase(db);original=globalThis.fetch;globalThis.fetch=async(input,options)=>{
 if(String(input).startsWith('https://opencode.ai/')){flashCalls++;if(rejectFlash)return new Response('down',{status:503});return new Response('data: '+JSON.stringify({model:CHAT_MODEL,choices:[{delta:{tool_calls:[{index:0,function:{name:'write_h3_prompt',arguments:JSON.stringify({integrated_multimodal_description:'[Shot 1] Live-action close-up of the complete chrome cylinder. The camera slowly pushes in while the product stays rigid. The same water flow continues through the final frame.'})}}]},finish_reason:'tool_calls'}]})+'\n\n');}
 return stub.fetch(input,options);
};});after(async()=>{globalThis.fetch=original;await db.close();});
function ctx(path,token='alice',body,extra={}){return {env,request:new Request('https://app.test'+path,{method:body?'POST':'GET',headers:{authorization:`Bearer ${token}`,...(body?{'content-type':'application/json'}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})})};}
async function write(action,id,data,expected=null,token='alice'){const r=await postStudio(ctx('/api/studio',token,{action,id,data,expected}));assert.ok(r.ok,await r.clone().text());return (await r.json()).value;}
let a,b,brand,project,scene;
test('authenticated API saves brand and storyboard and blocks foreign library access',async()=>{a=await user(db);b=await user(db);stub.users.set('alice',a);stub.users.set('bob',b);assert.equal((await getStudio(ctx('/api/studio','bad'))).status,401);brand=await write('save_brand',crypto.randomUUID(),{name:'Nebula',product:'Filtro',appearance:'Chrome',benefits:'Filtrar',claims:'Reduce cloro',avoid:'No curar calvicie',voiceName:'Voz guardada',voiceNotes:'Natural'});project=await write('create_project',crypto.randomUUID(),{title:'Anuncio',brandId:brand.id,referenceUrl:'',referenceNotes:'Azul',aspectRatio:'9:16',scenes:[]});scene={id:crypto.randomUUID(),text:'El agua atraviesa el filtro.',visual:'Acercamiento al cilindro cromado',start:0,end:5,imageAssetId:null,selectedVersionId:null};project=await write('save_project',project.id,{...project.data,scenes:[scene]},project.revision);assert.equal((await getStudio(ctx(`/api/studio?project=${project.id}`,'bob'))).status,404);const library=await (await getStudio(ctx('/api/studio'))).json();assert.equal(library.brands[0].data.voiceName,'Voz guardada');assert.equal(library.availability.voiceSynthesis,false);});
test('one-scene generation retry uses frozen context even after a project edit and maintenance',async()=>{await ready(db);const requestId=crypto.randomUUID(),data={requestId,sceneId:scene.id,instruction:'Quita el cabello del fondo'};const v=await write('version',project.id,data,project.revision);assert.equal(flashCalls,1);assert.match(v.request_payload.prompt,/integrated_multimodal_description/);const previousRevision=project.revision;project=await write('save_project',project.id,{...project.data,title:'Otro nombre'},project.revision);const c=ctx('/api/studio','alice',{action:'version',id:project.id,data,expected:previousRevision});c.env={...env,GENERATION_ENABLED:'false'};const retry=await postStudio(c);assert.equal(retry.status,202,await retry.clone().text());assert.equal((await retry.json()).value.id,v.id);assert.equal(flashCalls,1);assert.equal(await balance(db,a),11);const changed=await postStudio(ctx('/api/studio','alice',{action:'version',id:project.id,data:{...data,instruction:'Otra corrección'},expected:previousRevision}));assert.equal(changed.status,409);assert.equal((await renderWorker(ctx('/api/studio-worker','bad',{workerId:'cpu',action:'claim'}))).status,401);});
test('private voice upload is reusable without spending and cannot be opened by another account',async()=>{const bytes=new Uint8Array(48);bytes.set(new TextEncoder().encode('RIFF'));bytes.set(new TextEncoder().encode('WAVE'),8);const c={env,request:new Request('https://app.test/api/studio?upload=1&kind=voice',{method:'POST',headers:{authorization:'Bearer alice','content-type':'audio/wav','x-duration':'2','x-file-name':'voz.wav'},body:bytes})};const r=await postStudio(c);assert.equal(r.status,201,await r.clone().text());const asset=(await r.json()).asset;assert.equal((await getStudio(ctx(`/api/studio?asset=${asset.id}`,'bob'))).status,404);assert.ok((await (await getStudio(ctx(`/api/studio?asset=${asset.id}`))).json()).url.includes('token='));brand=await write('save_brand',brand.id,{...brand.data,voiceAssetId:asset.id},brand.revision);assert.equal(brand.data.voiceAssetId,asset.id);assert.equal(await balance(db,a),11);});

test('invalid H3 provider response reserves no GPU job or credits',async()=>{
 const before=await balance(db,a);rejectFlash=true;
 try{const requestId=crypto.randomUUID();const r=await postStudio(ctx('/api/studio','alice',{action:'version',id:project.id,expected:project.revision,data:{requestId,sceneId:scene.id,instruction:''}}));assert.equal(r.status,503);assert.equal((await r.json()).code,'H3_PROMPT_PROVIDER');assert.equal(await balance(db,a),before);assert.equal((await db.query('select count(*)::int n from generation_jobs where request_id=$1',[requestId])).rows[0].n,0);}finally{rejectFlash=false;}
});
