import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {database,user,ready,call,balance} from './helpers/database.mjs';
import {brandData,projectData,scenePrompt} from '../assets/studio-model.js';
let db;
before(async()=>{db=await database();});after(async()=>db.close());
beforeEach(async()=>db.exec('truncate studio_renders,studio_scene_versions,studio_projects,studio_brands,studio_assets,studio_workers,generation_jobs,generation_references,generation_workers,credit_ledger,purchases,credit_balances,customer_accounts,auth.users cascade;'));
const brand=()=>brandData({name:'Nebula',product:'Filtro de ducha',appearance:'Cromo, cilindro sobre regadera',benefits:'Filtración',claims:'Ayuda a reducir cloro libre',avoid:'No prometer curar calvicie',voiceName:'Voz de Nebula',voiceNotes:'Masculina, español',productAssetId:null,voiceAssetId:null});
const write=(u,action,id,data,expected=null)=>call(db,'studio_write',[u.id,action,id,JSON.stringify(data),expected]);
async function fixture(){const u=await user(db),brandId=crypto.randomUUID(),projectId=crypto.randomUUID();const b=await write(u,'save_brand',brandId,brand());const p=await write(u,'create_project',projectId,projectData({title:'Anuncio',brandId,referenceUrl:'',referenceNotes:'Explicación científica',aspectRatio:'9:16',narrationAssetId:null,scenes:[]}));return {u,b,p};}
async function upload(u,kind,duration=6){const id=crypto.randomUUID();await write(u,'register_asset',id,{kind,name:'Archivo',bucket:kind==='image'?'generation-references':'studio-media',storage_path:`${u.id}/${id}`,mime_type:kind==='image'?'image/png':kind==='clip'?'video/mp4':'audio/wav',size_bytes:100,duration_seconds:kind==='image'?null:duration});return id;}
async function storyboard(u,p){const audio=await upload(u,'narration',6),scenes=[0,1].map((n)=>({id:crypto.randomUUID(),text:n?'El agua atraviesa el filtro.':'Este es Nebula.',visual:n?'Mostrar el recorrido del agua':'Mostrar producto completo',start:n*3,end:n*3+3,imageAssetId:null,selectedVersionId:null}));return write(u,'save_project',p.id,projectData({...p.data,narrationAssetId:audio,timingConfirmed:true,scenes}),p.revision);}
async function version(u,p,index,{gpu=false,requestId=crypto.randomUUID(),instruction='Acerca el filtro'}={}){return write(u,'version',p.id,{sceneId:p.data.scenes[index].id,assetId:gpu?null:await upload(u,'clip'),requestId,instruction,prompt:scenePrompt(p,p.data.scenes[index].id,instruction)},p.revision);}
test('brand memory survives reload and later brand changes do not rewrite existing ads',async()=>{const {u,b,p}=await fixture();const voice=await upload(u,'voice');await write(u,'save_brand',b.id,{...b.data,voiceAssetId:voice,voiceName:'Nueva voz'},b.revision);let stored=(await call(db,'studio_read',[u.id,p.id])).project;assert.equal(stored.brand_snapshot.voiceName,'Voz de Nebula');stored=await write(u,'refresh_brand',p.id,{},p.revision);assert.equal(stored.brand_snapshot.voiceAssetId,voice);assert.equal(stored.revision,2);});
test('cross-account reads, asset references, edits and versions are rejected',async()=>{const {u,b,p}=await fixture(),other=await user(db);await assert.rejects(call(db,'studio_read',[other.id,p.id]),/STUDIO_NOT_FOUND/);await assert.rejects(write(other,'save_brand',b.id,b.data,b.revision),/STUDIO_NOT_FOUND/);const voice=await upload(u,'voice');await assert.rejects(write(other,'save_brand',crypto.randomUUID(),{...brand(),voiceAssetId:voice}),/STUDIO_ASSET_NOT_FOUND/);await assert.rejects(write(other,'save_project',p.id,p.data,p.revision),/STUDIO_NOT_FOUND/);});
test('optimistic concurrency prevents one tab silently overwriting another',async()=>{const {u,p}=await fixture();await write(u,'save_project',p.id,{...p.data,title:'Nuevo'},p.revision);await assert.rejects(write(u,'save_project',p.id,{...p.data,title:'Viejo'},p.revision),/STUDIO_CONFLICT/);assert.equal((await call(db,'studio_read',[u.id,p.id])).project.data.title,'Nuevo');});
test('revising exactly one scene preserves other versions, narration and order; request replay costs once',async()=>{const f=await fixture();await ready(db);let p=await storyboard(f.u,f.p);const v1=await version(f.u,p,0);p=await write(f.u,'select_version',p.id,{versionId:v1.id},p.revision);const v2=await version(f.u,p,1);p=await write(f.u,'select_version',p.id,{versionId:v2.id},p.revision);const requestId=crypto.randomUUID();const next=await version(f.u,p,0,{gpu:true,requestId});const replay=await write(f.u,'version',p.id,next.request_payload,p.revision);assert.equal(next.id,replay.id);assert.equal(await balance(db,f.u),11);const fetched=(await call(db,'studio_read',[f.u.id,p.id])).project;assert.deepEqual(fetched.data,p.data);assert.equal(next.snapshot.storyboard[1].id,p.data.scenes[1].id);assert.equal(next.snapshot.narrationAssetId,p.data.narrationAssetId);assert.match(next.request_payload.prompt,/Next: Mostrar el recorrido/);await assert.rejects(write(f.u,'version',p.id,{...next.request_payload,instruction:'Otra'},p.revision),/IDEMPOTENCY_CONFLICT/);});
test('old versions can be selected again without generating or spending',async()=>{const {u,p:base}=await fixture();let p=await storyboard(u,base);const a=await version(u,p,0),b=await version(u,p,0);p=await write(u,'select_version',p.id,{versionId:b.id},p.revision);p=await write(u,'select_version',p.id,{versionId:a.id},p.revision);assert.equal(p.data.scenes[0].selectedVersionId,a.id);assert.equal(p.data.scenes[1].selectedVersionId,null);assert.equal(await balance(db,u),12);assert.equal((await call(db,'studio_read',[u.id,p.id])).versions.length,2);});
test('render captures exact versions and voice, is fenced by lease, and old completions cannot overwrite newer edits',async()=>{const {u,p:base}=await fixture();let p=await storyboard(u,base);for(let n=0;n<2;n++){const v=await version(u,p,n);p=await write(u,'select_version',p.id,{versionId:v.id},p.revision);}await call(db,'studio_render_worker',['cpu','claim']);const req=crypto.randomUUID();const r=await write(u,'render',p.id,{requestId:req},p.revision);assert.equal((await write(u,'render',p.id,{requestId:req},p.revision)).id,r.id);const claim=await call(db,'studio_render_worker',['cpu','claim']);assert.deepEqual(claim.manifest.scenes.map(s=>s.id),p.data.scenes.map(s=>s.id));await assert.rejects(call(db,'studio_render_worker',['attacker','complete',r.id,claim.lease_token,true]),/LEASE_LOST/);await write(u,'save_project',p.id,{...p.data,title:'Nueva edición'},p.revision);await call(db,'studio_render_worker',['cpu','complete',r.id,claim.lease_token,true]);const data=await call(db,'studio_read',[u.id,p.id]);assert.equal(data.project.revision,p.revision+1);assert.equal(data.renders[0].project_revision,p.revision);assert.equal(data.renders[0].status,'succeeded');assert.equal(await balance(db,u),12);});
test('short clips and unselected scenes cannot be assembled',async()=>{const {u,p:base}=await fixture(),p=await storyboard(u,base);const a=await upload(u,'clip',1);await assert.rejects(write(u,'version',p.id,{sceneId:p.data.scenes[0].id,assetId:a,requestId:crypto.randomUUID(),instruction:'',prompt:'valid prompt'},p.revision),/STUDIO_CLIP_TOO_SHORT/);await call(db,'studio_render_worker',['cpu','claim']);await assert.rejects(write(u,'render',p.id,{requestId:crypto.randomUUID()},p.revision),/STUDIO_NOT_READY/);});
test('RLS hides other brands and the browser cannot mutate studio records or call privileged functions',async()=>{const a=await fixture(),b=await fixture();await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a.u.id]);await db.exec('set role authenticated');try{assert.deepEqual((await db.query('select user_id from studio_brands')).rows.map(r=>r.user_id),[a.u.id]);await assert.rejects(db.query("update studio_projects set data='{}'"),/permission denied/);await assert.rejects(call(db,'studio_read',[b.u.id,b.p.id]),/permission denied/);await assert.rejects(db.query('select * from studio_assets'),/permission denied/);}finally{await db.exec('reset role');}const rows=(await db.query("select relrowsecurity from pg_class where relname like 'studio_%' and relkind='r'")).rows;assert.equal(rows.length,10);assert.ok(rows.every(x=>x.relrowsecurity));});
test('timeline and prompt rules reject overlap and retain brand limits, neighbors and correction',()=>{assert.throws(()=>projectData({title:'x',referenceUrl:'',referenceNotes:'',aspectRatio:'9:16',scenes:[{id:crypto.randomUUID(),text:'Hola',visual:'Producto',start:1,end:4}]}),/STUDIO_TIMELINE/);const p={brand_snapshot:brand(),data:{scenes:[{id:'first',text:'Uno',visual:'Producto',start:0,end:3},{id:'second',text:'Dos',visual:'Agua',start:3,end:6}],referenceNotes:'Azul'}};const prompt=scenePrompt(p,'second','Quita el cabello');assert.match(prompt,/No prometer curar calvicie/);assert.match(prompt,/Previous: Producto/);assert.match(prompt,/Correction: Quita el cabello/);assert.ok(prompt.length<=1600);});
